#!/bin/zsh

if [ -d /etc/X11/xinit/xinitrc.d ]; then
    for f in /etc/X11/xinit/xinitrc.d/*; do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi

[[ -f $HOME/etc/xresources ]] && xrdb -merge $HOME/etc/xresources
start-pulseaudio-x11
wmname LG3D
numlockx on
nitrogen --restore
compton --config $HOME/etc/compton.conf &
pcmanfm -d &

xautolock -time 30 -locker "i3lock -g" &
xsetroot -name " "
xset -b  #Turn off PC Speaker
#xbindkeys
xrdb -merge $HOME/etc/xresources

xmodmap -e "keycode 108 = Super_L"  # reassign Alt_R to Super_L
xmodmap -e "remove mod1 = Super_L"  # make sure X keeps it out of the mod1 group

while true; do
    ( sleep 2 & $HOME/etc/dwm/dwmstatus.sh ) &
    dwm &> $HOME/log/dwm.log
    pkill dwmstatus
    pkill dzen2
    clear
done
