#!/bin/zsh
alias zcl="clear && echo -e \"${blu}ArchLinux${rst} (${wht}$(uname -r)${rst})\""
alias zup="source ~/.zshrc"
alias mpd="mpd $CONFDIR/mpd/mpd.conf"
alias icanhazip="curl ipv6.icanhazip.com;curl ipv4.icanhazip.com"
alias suspend="sudo systemd start systemd-suspend.service"
alias pacman="sudo pacman"
alias systemctl="sudo systemctl"
alias subl="subl 2> /dev/null"
alias scan="scanimage -d pixma --format=tiff >"
alias gitlog="git log --all --graph --pretty=format:'%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit --date=relative"
