alias zcl="clear"
alias zup="source ~/.zshrc"
alias mpd="mpd ~/etc/mpd/mpd.conf"
alias icanhazip="curl ipv6.icanhazip.com;curl ipv4.icanhazip.com"
alias suspend="sudo systemd start systemd-suspend.service"
alias pacman="sudo pacman"
alias systemctl="sudo systemctl"
alias subl="subl 2> /dev/null"
