BLK=$(grep "color0:" /home/komrade/etc/xresources | sed -e 's/ //g' | awk -F : '{print $2}')
RED=$(grep "color1:" /home/komrade/etc/xresources | sed -e 's/ //g' | awk -F : '{print $2}')
GRN=$(grep "color2:" /home/komrade/etc/xresources | sed -e 's/ //g' | awk -F : '{print $2}')
YLW=$(grep "color3:" /home/komrade/etc/xresources | sed -e 's/ //g' | awk -F : '{print $2}')
BLU=$(grep "color4:" /home/komrade/etc/xresources | sed -e 's/ //g' | awk -F : '{print $2}')
PNK=$(grep "color5:" /home/komrade/etc/xresources | sed -e 's/ //g' | awk -F : '{print $2}')
CYN=$(grep "color6:" /home/komrade/etc/xresources | sed -e 's/ //g' | awk -F : '{print $2}')
WHT=$(grep "color7:" /home/komrade/etc/xresources | sed -e 's/ //g' | awk -F : '{print $2}')

BBLK=$(grep "color8:" /home/komrade/etc/xresources | sed -e 's/ //g' | awk -F : '{print $2}')
BRED=$(grep "color9:" /home/komrade/etc/xresources | sed -e 's/ //g' | awk -F : '{print $2}')
BGRN=$(grep "color10:" /home/komrade/etc/xresources | sed -e 's/ //g' | awk -F : '{print $2}')
BYLW=$(grep "color11:" /home/komrade/etc/xresources | sed -e 's/ //g' | awk -F : '{print $2}')
BBLU=$(grep "color12:" /home/komrade/etc/xresources | sed -e 's/ //g' | awk -F : '{print $2}')
BPNK=$(grep "color13:" /home/komrade/etc/xresources | sed -e 's/ //g' | awk -F : '{print $2}')
BCYN=$(grep "color14:" /home/komrade/etc/xresources | sed -e 's/ //g' | awk -F : '{print $2}')
BWHT=$(grep "color15:" /home/komrade/etc/xresources | sed -e 's/ //g' | awk -F : '{print $2}')