source $HOME/etc/zsh/zshenv

clear

echo -e "Please wait, updating ${BLU}pacman${WHT} repos..."
sudo pacman -Sy &> $HOME/log/pacman.log
sudo pacman -Qu | wc -l > $HOME/log/updates.log

mpd -v &> $HOME/log/mpd.log &

clear
echo -e "Welcome to ${blu}ArchLinux${rst}, $(whoami)!\n"
